pet_shop/pet_shop/Controllers/CustomerController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using pet_shop.Models;
using pet_shop.MySQLRepository;

namespace pet_shop.Controllers
{
    public class CustomerController : Controller
    {
       
        public ActionResult Index()
        {

            if (Globals.user.login == null)
            {
                Globals.error_code = 1;
                return RedirectToAction("Index", "Home");
            }

            var rep = new PetMySQLRepository();
            var shopRep = new ShopMySQLRepository();

            var pets = rep.GetPets();
            
            var DisplayInfo = new List<DisplayInfo>();
            var petsInfo = new List<int>(); // 0 = shop_id, 1 = price, 2 = pet availability

            for (int i = 0; i < pets.Count(); i++)
            {
                petsInfo = rep.GetShopIdByPetId(pets[i].pet_id);
                if (petsInfo[2] == 1)
                {
                    DisplayInfo.Add(new DisplayInfo(pets[i], shopRep.GetShopAdressByShopId(petsInfo[0]), petsInfo[1]));
                }
            }

            return View(DisplayInfo);
        }


        [HttpPost]
        public ActionResult CreateOrder(IFormCollection collection)
        {
            var rep = new OrderMySqlRepository();
            var petRep = new PetMySQLRepository();
            var petId = Convert.ToInt32(collection["petId"]);
            var order = new Order(Globals.user.id, petId);

            rep.CreateOrder(order);

            petRep.ChangePetAvailability(petId, "no");

            return RedirectToAction("Index");
        }

        // POST: CustomerController/DeletePet
        [HttpPost]
        public ActionResult DeletePet(IFormCollection collection)
        {
            var rep = new PetMySQLRepository();
            Console.WriteLine("DeletePetById(" + collection["petId"] + ");");
            rep.DeletePetById(Convert.ToInt32(collection["petId"]));
            return RedirectToAction("Index");
        }

        public ActionResult ShowOrders()
        {
            var petRep = new PetMySQLRepository();
            var orderRep = new OrderMySqlRepository();
            var shopRep = new ShopMySQLRepository();

            var orderedPetsIds = orderRep.GetOrderedPets(Globals.user.id);

            var DisplayInfo = new List<DisplayInfo>();
            var petsInfo = new List<int>();

            for (int i = 0; i < orderedPetsIds.Count(); i++)
            {
                petsInfo = petRep.GetShopIdByPetId(orderedPetsIds[i][0]);
                DisplayInfo.Add(new DisplayInfo(petRep.GetPetInfoById(orderedPetsIds[i][0]), orderedPetsIds[i][1], shopRep.GetShopAdressByShopId(petsInfo[0]), petsInfo[1]));
            }
            return View(DisplayInfo);
        }

        [HttpPost]
        public ActionResult RefuseOrder(IFormCollection collection)
        {
            var orderRep = new OrderMySqlRepository();
            var petRep = new PetMySQLRepository();
            var orderNum = Convert.ToInt32(collection["orderNumber"]);
            var petId = Convert.ToInt32(collection["petId"]);
            
            orderRep.DeleteOrderByNumber(orderNum);

            petRep.ChangePetAvailability(petId, "yes");

            return RedirectToAction("ShowOrders");
        }

        public ActionResult ShowFilteredTable()
        {
            var shopRep = new ShopMySQLRepository();
            var shops = shopRep.GetShops();
            var adresses = new List<string>();
            for (int i = 0; i < shops.Count(); i++)
            {
                adresses.Add(shops[i].adress);
            }
            ViewBag.Shops = adresses;

            return View(Globals.DisplayInfoForTables);
        }

        [HttpPost]
        public ActionResult Filter(IFormCollection collection)
        {
            var rep = new PetMySQLRepository();
            int canSwim = 0, canReproduce = 0;
            if (collection["canSwim"] == "Yes")
                canSwim = 1;
            else if (collection["canSwim"] == "Any")
                canSwim = 2;

            if (collection["reproduceAbility"] == "Yes")
                canReproduce = 1;
            else if (collection["reproduceAbility"] == "Any")
                canReproduce = 2;
            Globals.DisplayInfoForTables = rep.FilterResult(collection["petType"], collection["gender"],
                canSwim, canReproduce,
                Convert.ToInt32(collection["priceFrom"]), Convert.ToInt32(collection["priceTo"]),
                collection["adress"]);
          

            return RedirectToAction("ShowFilteredTable");
        }

    }
}

pet_shop/pet_shop/Views/Customer/Index.cshtml
<h1>Hello Customer</h1>

<div class="col-2">
    <form asp-action="ShowOrders">
        <button class="btn-outline-primary" type="submit">Show My Orders</button>
    </form>

    <form asp-action="ShowFilteredTable">
        <button class="btn-outline-primary" type="submit">Search with Filters</button>
    </form>
</div>


<table class="table-primary table-striped col-md-12">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Name</th>
            <th scope="col">Pet type</th>
            <th scope="col">Age</th>
            <th scope="col">Color</th>
            <th scope="col">Swim Ability</th>
            <th scope="col">Reproduce Ability</th>
            <th scope="col">Gender</th>
            <th scope="col">Pet Breed</th>
            <th scope="col">Price</th>
            <th scope="col">Shop Adress</th>
        </tr>
    </thead>
    <tbody>
        @foreach (pet_shop.Models.DisplayInfo display in Model)
        {
        <tr>
            <td>@display.pet_id</td>
            <td>@display.name</td>
            <td>@display.pet_type</td>
            <td>@display.age</td>
            <td>@display.color</td>
            <td>@display.can_swim</td>
            <td>@display.reproduce_ability</td>
            <td>@display.gender</td>
            <td>@display.pet_breed</td>
            <td>@display.price</td>
            <td>@display.adress</td>
            <td>
                <form id="data1" asp-action="CreateOrder" method="post">
                    <button class="btn-warning" type="submit">Create Order</button>
                    <input type="hidden" name="petId" value=@display.pet_id />
                </form>
            </td>
        </tr>
        }
    </tbody>
</table>

pet_shop/pet_shop/Views/Customer/ShowFilteredTable.cshtml
<h1>Testing Filter</h1>

<!--filter input-->
<form class="row g-3" method="post" asp-controller="Customer" asp-action="Filter">

    <div class="col-md-10">
        <label for="validationDefault08" class="form-label">Pet type</label>
        <select class="form-select" id="validationDefault08" required name="petType">
            <option selected>Any</option>
            <option>Cat</option>
            <option>Dog</option>
            <option>Raccoon</option>
            <option>Fox</option>
            <option>Hedgehog</option>
        </select>
    </div>

    <div class="col-md-10">
        <label for="validationDefault06" class="form-label">Pet Gender</label>
        <select class="form-select" id="validationDefault06" required name="gender">
            <option selected>Any</option>
            <option>Male</option>
            <option>Female</option>
        </select>
    </div>

    <div class="col-md-10">
        <label for="validationDefault07" class="form-label">Pet Swim ability</label>
        <select class="form-select" id="validationDefault07" required name="canSwim">
            <option selected>Any</option>
            <option>Yes</option>
            <option>No</option>
        </select>
    </div>

    <div class="col-md-10">
        <label for="validationDefault10" class="form-label">Pet reproduce ability</label>
        <select class="form-select" id="validationDefault10" required name="reproduceAbility">
            <option selected>Any</option>
            <option>Yes</option>
            <option>No</option>
        </select>
    </div>

    <div class="col-md-4">
        <label for="validationDefault04" class="form-label">Price From</label>
        <input type="text" class="form-control" id="validationDefault04" name="priceFrom" value="0" required>
    </div>
    <div class="col-md-4">
        <label for="validationDefault05" class="form-label">Price To</label>
        <input type="text" class="form-control" id="validationDefault05" name="priceTo" value="1000000" required>
    </div>

    <div class="col-md-10">
        <label for="validationDefault09" class="form-label">Shops</label>
        <select class="form-select" id="validationDefault09" required name="adress">
            <option selected>Any</option>
            @foreach (string adress in ViewBag.Shops)
            {
            <option>@adress</option>
            }
        </select>
    </div>


    <div class="col-12">
        <button class="btn btn-primary" type="submit">Start Searching</button>
    </div>
</form>
<!--filter input-->
<!--filter output-->
<table class="table-primary table-striped col-md-12">
    <thead>
        <tr>
            <th scope="col">id</th>
            <th scope="col">Name</th>
            <th scope="col">Pet type</th>
            <th scope="col">Age</th>
            <th scope="col">Color</th>
            <th scope="col">Swim Ability</th>
            <th scope="col">Reproduce Ability</th>
            <th scope="col">Gender</th>
            <th scope="col">Pet Breed</th>
            <th scope="col">Price</th>
            <th scope="col">Shop Adress</th>
        </tr>
    </thead>
    <tbody>
        @foreach (pet_shop.Models.DisplayInfo display in Model)
        {
        <tr>
            <td>@display.pet_id</td>
            <td>@display.name</td>
            <td>@display.pet_type</td>
            <td>@display.age</td>
            <td>@display.color</td>
            <td>@display.can_swim</td>
            <td>@display.reproduce_ability</td>
            <td>@display.gender</td>
            <td>@display.pet_breed</td>
            <td>@display.price</td>
            <td>@display.adress</td>
            <td>
                <form id="data1" asp-action="CreateOrder" method="post">
                    <button class="btn-warning" type="submit">Create Order</button>
                    <input type="hidden" name="petId" value=@display.pet_id />
                </form>
            </td>
        </tr>
        }
    </tbody>
</table>
<!--filter output-->

pet_shop/pet_shop/Views/Customer/ShowOrders.cshtml
<h1>My Orders:</h1>

<table class="table-primary table-striped col-md-12">
    <thead>
        <tr>
            <th scope="col">order number</th>
            <th scope="col">id</th>
            <th scope="col">Name</th>
            <th scope="col">Pet type</th>
            <th scope="col">Age</th>
            <th scope="col">Color</th>
            <th scope="col">Swim Ability</th>
            <th scope="col">Reproduce Ability</th>
            <th scope="col">Gender</th>
            <th scope="col">Pet Breed</th>
            <th scope="col">Price</th>
            <th scope="col">Shop Adress</th>
        </tr>
    </thead>
    <tbody>
        @foreach (pet_shop.Models.DisplayInfo display in Model)
        {
        <tr>
            <td>@display.order_number</td>
            <td>@display.pet_id</td>
            <td>@display.name</td>
            <td>@display.pet_type</td>
            <td>@display.age</td>
            <td>@display.color</td>
            <td>@display.can_swim</td>
            <td>@display.reproduce_ability</td>
            <td>@display.gender</td>
            <td>@display.pet_breed</td>
            <td>@display.price</td>
            <td>@display.adress</td>
            <td>
                <form id="data1" asp-action="RefuseOrder" method="post">
                    <button class="btn-warning" type="submit">Refuse Order</button>
                    <input type="hidden" name="orderNumber" value=@display.order_number />
                    <input type="hidden" name="petId" value=@display.pet_id />
                </form>
            </td>
        </tr>
        }
    </tbody>
</table>