pet_shop/pet_shop/Controllers/VendorController.cs
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using pet_shop.MySQLRepository;
using pet_shop.Models;

namespace pet_shop.Controllers
{
    public class VendorController : Controller
    {
        // GET: VendorController
        public ActionResult Index()
        {
            if (Globals.user.login == null)
            {
                Globals.error_code = 1;
                return RedirectToAction("Index", "Home");
            }

            var rep = new UserMySQLRepository();
            string role = rep.GetUserByLogin(Globals.user.login).role;

            if (role == "vendor" || role == "admin")
            {
                return View();
            }

            Globals.error_code = 2;
            return RedirectToAction("Index", "Home");

        }

        public ActionResult ShowAllOrders()
        {
            var rep = new OrderMySqlRepository();
            var orders = rep.GetOrders();
            return View(orders);
        }

        public ActionResult PetCreator()
        {
            var shopRep = new ShopMySQLRepository();
            var shops = shopRep.GetShops();
            var adresses = new List<string>();
            for (int i = 0; i < shops.Count(); i++)
            {
                adresses.Add(shops[i].adress);
            }
            ViewBag.Shops = adresses;
            return View();
        }

       

        // POST: VendorController/Create
        [HttpPost]
        public ActionResult AddNewPet(IFormCollection collection)
        {
            try
            { 
                var petRep = new PetMySQLRepository();
                var shopRep = new ShopMySQLRepository();

                int shopId = shopRep.GetShopIdByAdress(collection["shop_id"]);
                if (shopId == -10)
                {
                    Console.WriteLine("AddNewPet: There is no such shop");
                    return RedirectToAction("Index");
                }

                int petId = petRep.GetPetNewId();
                Console.WriteLine("PetId = " + petId + "\nshopId = " + shopId);

                var pet = new Pet(petId, shopId, Convert.ToInt32(collection["price"]));
                petRep.AddPetPrice(pet);

                int canSwinBit = 0;
                int canReproduceBit = 0;

                if (collection["can_swim"] == "Yes")
                    canSwinBit = 1;
                if (collection["reproduce_ability"] == "Yes")
                    canReproduceBit = 1;

                var PI = new PetInfo(pet.pet_id, collection["pet_type"], collection["name"],
                    Convert.ToInt32(collection["age"]), collection["color"],canSwinBit, canReproduceBit, collection["gender"], collection["pet_breed"]);
                petRep.AddPetInfo(PI);

                return RedirectToAction("Index", "Home");
            }
            catch (Exception e)
            {
                Console.WriteLine("Error: " + e);
                return RedirectToAction("Error", "Home");
            }
        }
        [HttpPost]
        public ActionResult RefuseOrder(IFormCollection collection)
        {
            var orderRep = new OrderMySqlRepository();
            var petRep = new PetMySQLRepository();
            var orderNum = Convert.ToInt32(collection["orderNumber"]);
            var petId = Convert.ToInt32(collection["petId"]);

            orderRep.DeleteOrderByNumber(orderNum);

            petRep.ChangePetAvailability(petId, "yes");

            return RedirectToAction("ShowAllOrders");
        }

        [HttpPost]
        public ActionResult CloseOrder(IFormCollection collection)
        {
            var petRep = new PetMySQLRepository();
            var orderRep = new OrderMySqlRepository();

            orderRep.DeleteOrderByNumber(Convert.ToInt32(collection["orderNumber"]));
            petRep.DeletePetById(Convert.ToInt32(collection["petId"]));
            return RedirectToAction("ShowAllOrders");
        }
    }
}

pet_shop/pet_shop/Views/Vendor/Index.cshtml
<h1>Hello Vendor</h1>

<p>
    <a class="btn btn-outline-primary btn-lg" asp-controller="Vendor" asp-action="ShowAllOrders" type="submit">Show All Orders</a>
</p>
<p>
    <a class="btn btn-outline-primary btn-lg" asp-controller="Vendor" asp-action="PetCreator" type="submit">Create Pet</a>
</p>

pet_shop/pet_shop/Views/Vendor/PetCreator.cshtml
<form class="row g-3" method="post" asp-controller="Vendor" asp-action="AddNewPet">
    <div class="col-md-4">
        <label for="validationDefault02" class="form-label">Pet Name</label>
        <input type="text" class="form-control" id="validationDefault02" name="name" required>
    </div>
    <div class="col-md-4">
        <label for="validationDefault03" class="form-label">Pet Age</label>
        <input type="text" class="form-control" id="validationDefault03" name="age" required>
    </div>
    <div class="col-md-4">
        <label for="validationDefault04" class="form-label">Pet Color</label>
        <input type="text" class="form-control" id="validationDefault04" name="color" required>
    </div>
    <div class="col-md-4">
        <label for="validationDefault05" class="form-label">Pet Breed</label>
        <input type="text" class="form-control" id="validationDefault05" name="pet_breed" required>
    </div>
    <div class="col-md-10">
        <label for="validationDefault06" class="form-label">Pet Gender</label>
        <select class="form-select" id="validationDefault06" required name="gender">
            <option selected disabled value="">Choose...</option>
            <option>Male</option>
            <option>Female</option>
        </select>
    </div>

    <div class="col-md-10">
        <label for="validationDefault07" class="form-label">Pet Swim ability</label>
        <select class="form-select" id="validationDefault07" required name="can_swim">
            <option selected disabled value="">Choose...</option>
            <option>Yes</option>
            <option>No</option>
        </select>
    </div>

    <div class="col-md-10">
        <label for="validationDefault07" class="form-label">Pet reproduce ability</label>
        <select class="form-select" id="validationDefault07" required name="reproduce_ability">
            <option selected disabled value="">Choose...</option>
            <option>Yes</option>
            <option>No</option>
        </select>
    </div>

    <div class="col-md-10">
        <label for="validationDefault08" class="form-label">Pet type</label>
        <select class="form-select" id="validationDefault08" required name="pet_type">
            <option selected disabled value="">Choose...</option>
            <option>Cat</option>
            <option>Dog</option>
            <option>Raccoon</option>
            <option>Fox</option>
            <option>Hedgehog</option>
        </select>
    </div>

    <div class="col-md-10">
        <label for="validationDefault09" class="form-label">Shops</label>
        <select class="form-select" id="validationDefault09" required name="shop_id">
            <option selected disabled value="">Choose...</option>
            @foreach (string adress in ViewBag.Shops)
            {
            <option>@adress</option>
            }
        </select>
    </div>
    <div class="col-md-4">
        <label for="validationDefault01" class="form-label">Pet Price</label>
        <input type="text" class="form-control" id="validationDefault01" name="price" required>
    </div>
    <div class="col-12">
        <button class="btn btn-primary" type="submit">Add Pet</button>
    </div>
</form>

pet_shop/pet_shop/Views/Vendor/ShowAllOrders.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}

<h1>All Orders:</h1>

<table class="table-primary table-striped col-md-12">
    <thead>
        <tr>
            <th scope="col">order number</th>
            <th scope="col">user id</th>
            <th scope="col">pet id</th>
        </tr>
    </thead>
    <tbody>
        @foreach (pet_shop.Models.Order display in Model)
        {
        <tr>
            <td>@display.order_number</td>
            <td>@display.user_id</td>
            <td>@display.pet_id</td>
            <td>
                <form id="data2" asp-action="RefuseOrder" method="post">
                    <button class="btn-warning" type="submit">Refuse Order</button>
                    <input type="hidden" name="orderNumber" value=@display.order_number />
                    <input type="hidden" name="petId" value=@display.pet_id />
                </form>
            </td>
            <td>
                <form id="data1" asp-action="CloseOrder" method="post">
                    <button class="btn-danger" type="submit">Close Order</button>
                    <input type="hidden" name="orderNumber" value=@display.order_number />
                    <input type="hidden" name="petId" value=@display.pet_id />
                </form>
            </td>
        </tr>
        }
    </tbody>
</table>